- name: install apache on web servers Fedora
  tags: apache
  ansible.builtin.dnf:
    name:
      - "{{ apache_package }}"
    use_backend: dnf4
  when: ansible_distribution == "Fedora"

- name: install apache on web servers Ubuntu
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"
  when: ansible_distribution == "Ubuntu"


- name: ensure apache is running
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin jacobbrenkus925@gmail.com
  when: ansible_distribution == "Fedora"
  notify: restart_apache

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
